=== LXiong/multimedia-info-distribute-and-manage-system/policy-man/policy-man-db/src/main/dbschema/dbschema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.dwangel.com/dbschema"
	xmlns="http://www.dwangel.com/dbschema" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:element name="schema">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:choice>
				<xsd:element ref="key" />
				<xsd:element ref="complex-key" />
			</xsd:choice>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="column" />
				<xsd:element ref="column-group" />
				<xsd:element ref="default-condition" />
				<xsd:element ref="default-order-by-set" />
				<xsd:element ref="result-map" />
				<xsd:element ref="disabled" />
				<xsd:element ref="alias" />
				<xsd:element ref="aliasColumns" />
			</xsd:choice>
		</xsd:sequence>
		
		<xsd:attribute name="name" type="xsd:string">
			<xsd:annotation>
					<xsd:documentation><![CDATA[
	The unique name of a model schema. If the table name is not definded, used as database table name.
					]]></xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="modelName" type="xsd:string">
			<xsd:annotation>
					<xsd:documentation><![CDATA[
	The unique name of the model Java class.
					]]></xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		
		<xsd:attribute name="tableName" type="xsd:string">
			<xsd:annotation>
					<xsd:documentation><![CDATA[
	The unique name of the model Java class.
					]]></xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		
		<xsd:attribute name="paged" type="xsd:boolean">
			<xsd:annotation>
					<xsd:documentation><![CDATA[
	Whether use pagination.
					]]></xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
</xsd:element>

	<xsd:simpleType name="generatorChoice">
		<xsd:restriction base="xsd:NMTOKEN">
			<xsd:enumeration value="native"/>
			<xsd:enumeration value="sequence"/>
			<xsd:enumeration value="uuid"/>
		</xsd:restriction>
	</xsd:simpleType>

<xsd:element name="key">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="columnDef">
				<xsd:attribute name="generator"  type="generatorChoice">
					<xsd:annotation>
							<xsd:documentation><![CDATA[
   This attribute defines how to generate a key. The choice is native, sequence, uuid. Currently only sequence is supported.
							]]></xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

<xsd:element name="complex-key">
	<xsd:complexType>
		<xsd:choice minOccurs="1" maxOccurs="unbounded">
			<xsd:element ref="column" />
		</xsd:choice>
	</xsd:complexType>
</xsd:element>

	<xsd:complexType name="columnDef">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="type" type="xsd:string" use="required"/>
		<xsd:attribute name="length" type="xsd:integer"/>
		<xsd:attribute name="noUpdate" type="xsd:boolean"/>
		<xsd:attribute name="defaultValue" type="xsd:string"/>
		<xsd:attribute name="updateValue" type="xsd:string"/>
		<xsd:attribute name="insertValue" type="xsd:string"/>
	</xsd:complexType>
<xsd:element name="column" type="columnDef" />

<xsd:element name="column-group">
	<xsd:complexType>
		<xsd:attribute name="name" type="xsd:string" />
	</xsd:complexType>
</xsd:element>

	<xsd:complexType name="searchConditionType">
		<xsd:attribute name="column" type="xsd:string"  />
		<xsd:attribute name="value" type="xsd:string"  />
		<xsd:attribute name="low" type="xsd:string"  />
		<xsd:attribute name="high" type="xsd:string" />
	</xsd:complexType>
	<xsd:complexType name="orderBy">
		<xsd:attribute name="column" type="xsd:string" />
		<xsd:attribute name="asc" type="xsd:boolean" />
	</xsd:complexType>
	
<xsd:element name="default-condition">
	<xsd:complexType >
		<xsd:sequence>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="match" />
				<xsd:element ref="match-value" />
				<xsd:element ref="like" />
				<xsd:element ref="between" />
				<xsd:element ref="order-by" />
			</xsd:choice>
		</xsd:sequence>
	</xsd:complexType>
</xsd:element>
	<xsd:element name="match" type="searchConditionType" />
	<xsd:element name="match-value" type="searchConditionType" />
	<xsd:element name="like" type="searchConditionType" />
	<xsd:element name="between" type="searchConditionType"/>
	<xsd:element name="order-by" type="orderBy"/>

<xsd:element name="default-order-by-set">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element ref="order-by"/>
		</xsd:sequence>
	</xsd:complexType>
</xsd:element>

	<xsd:complexType name="relatedCollection">
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element ref="collection" />
			<xsd:element ref="association" />
		</xsd:choice>
		<xsd:attribute name="schemaName" type="xsd:string" />
		<xsd:attribute name="alias" type="xsd:string" />
		<xsd:attribute name="property" type="xsd:string" />
	</xsd:complexType>
	
	<xsd:complexType name="relatedAssoc">
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element ref="collection" />
			<xsd:element ref="association" />
		</xsd:choice>
		<xsd:attribute name="schemaName" type="xsd:string" />
		<xsd:attribute name="alias" type="xsd:string" />
		<xsd:attribute name="property" type="xsd:string" />
		<xsd:attribute name="column" type="xsd:string" />
	</xsd:complexType>
<xsd:element name="result-map">
	<xsd:complexType>
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element ref="collection" />
			<xsd:element ref="association" />
		</xsd:choice>
		<xsd:attribute name="name" type="xsd:string" />
		<xsd:attribute name="alias" type="xsd:string" />
	</xsd:complexType>
</xsd:element>
	<xsd:element name="collection" type="relatedCollection"></xsd:element>
	<xsd:element name="association" type="relatedAssoc"></xsd:element>
	
<xsd:element name="disabled">
	<xsd:complexType>
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element ref="method" />
		</xsd:choice>
	</xsd:complexType>
</xsd:element>
	<xsd:element name="method" />
	
<xsd:element name="alias">
	<xsd:complexType>
		<xsd:attribute name="name" type="xsd:string" />
	</xsd:complexType>
</xsd:element>

<xsd:element name="aliasColumns">
	<xsd:complexType>
		<xsd:attribute name="name" type="xsd:string" />
	</xsd:complexType>
</xsd:element>

<xsd:element name="description">
	<xsd:annotation>
		<xsd:documentation><![CDATA[
Contains informative text describing the purpose of the enclosing element.
		]]></xsd:documentation>
	</xsd:annotation>
	<xsd:complexType mixed="true">
		<xsd:choice minOccurs="0" maxOccurs="unbounded"/>
	</xsd:complexType>
</xsd:element>

</xsd:schema>

=== LXiong/multimedia-info-distribute-and-manage-system/policy-man/policy-man-db/src/main/dbschema/PolicyMedia.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema name="policy_media" modelName="PolicyMedia"
	xmlns="http://www.dwangel.com/dbschema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.dwangel.com/dbschema dbschema.xsd"
>
<!-- This model is used to define play resource in a policy -->
	<complex-key>
		<column name="policy_id" type="number"  />
		<column name="name" type="nvarchar" length="64" />
	</complex-key>
	<column name="type" type="char" length="1" />
	<column name="content" type="nvarchar" length="200" />
	<column name="length" type="number" />
	<column name="play_count" type="number" />
	
	<result-map name="withVideo" alias="pm">
		<association alias="v" column="content" property="video" schemaName="videos" />
	</result-map>
</schema>

=== LXiong/multimedia-info-distribute-and-manage-system/policy-man/policy-man-db/src/main/dbschema/PolicyRec.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema name="policyRec" modelName="PolicyRec" tableName="policy" paged="true"
xmlns="http://www.dwangel.com/dbschema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.dwangel.com/dbschema dbschema.xsd">
	<key name="policyId" type="number" generator="native"></key>
	<column name="policy_number" type="number" />
	<column name="comments" type="varchar" length="300"/>
	<column name="begin_at" type="datetime" />
	<column name="end_at" type="datetime" />
	<column name="md5" type="varchar" length="64" />
	<column name="size_bytes" type="number" />
	<column name="update_time" type="datetime" updateValue="SYSDATE"/>
	<column name="created_at" type="datetime"/>
	<column name="file_path" type="varchar" length="100"/>
	
<!--	<result-map name="withTimeBuckets">-->
<!--		<collection  alias="time_buckets" schemaName="time_buckets" property="timeBuckets"/>		-->
<!--	</result-map>-->
<!--	<result-map name="withPlayItems">-->
<!--		<collection  alias="play_items" schemaName="play_items" property="playItems"/>		-->
<!--	</result-map>-->
<!-- 	<result-map name="withLayout" alias="policy"> -->
<!-- 		<collection  alias="layouts" schemaName="timed_layout" property="layoutList"/>		 -->
<!-- 	</result-map> -->

</schema>

=== LXiong/multimedia-info-distribute-and-manage-system/policy-man/policy-man-db/src/main/dbschema/ManRole.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema name="man_roles" modelName="Role" paged="true"
xmlns="http://www.dwangel.com/dbschema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.dwangel.com/dbschema dbschema.xsd"
>
	<key name="id" type="number" generator="native"></key>
	<column name="name" type="nvarchar" length="30" />
	<column name="description" type="nvarchar" length="100" />
	<column name="enabled" type="boolean" length="1" defaultValue="'1'"/>
	<column-group name="trackModify" />
	
	<default-condition>
		<match column="id" />
		<match column="enabled" />
	</default-condition>
</schema>

=== LXiong/multimedia-info-distribute-and-manage-system/policy-man/policy-man-db/src/main/dbschema/Area.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema name="area" modelName="Area"
	xmlns="http://www.dwangel.com/dbschema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.dwangel.com/dbschema dbschema.xsd"
>
	<key name="id" type="number" generator="native"></key>	
		<column name="layoutid" type="number"  />
		<column name="name" type="varchar"  length="100" />
		<column name="lcomment" type="varchar" length="200"  />
		<!--
		<option value="1">视频</option>
		<option value="2">图片</option>
		<option value="3">文字</option>
		<option value="4">时间</option>
		<option value="5">天气</option> 
		 -->
		<column name="type" type="varchar" length="2" />
		<column name="left" type="number" />
		<column name="top" type="number" />
		<column name="height" type="number" />
		<column name="width" type="number" />
		<column name="zindex" type="number" />
		
		<column name="time_format" type="varchar" length="50"/>
		
		<alias name="area"/>
</schema>

=== LXiong/multimedia-info-distribute-and-manage-system/policy-man/policy-man-db/src/main/dbschema/UploadingVideo.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema name="uploading_videos" modelName="UploadingVideo"
paged="true"
xmlns="http://www.dwangel.com/dbschema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.dwangel.com/dbschema dbschema.xsd"
>
	<key name="id" type="number" generator="native"></key>
	<column name="code" type="varchar" length="64" />
	<column name="file_name" type="nvarchar" length="100" />
	<column name="origin_name" type="nvarchar" length="100" />
	<column name="current_size" type="number" />
	<column name="expected_size" type="number" />
	<column name="last_modified_time" type="datetime" />
	<column name="uploaded" type="boolean" length="1" />
</schema>

=== LXiong/multimedia-info-distribute-and-manage-system/policy-man/policy-man-db/src/main/dbschema/TimedArea.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema name="timed_area" modelName="TimedArea"
	xmlns="http://www.dwangel.com/dbschema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.dwangel.com/dbschema dbschema.xsd"
>
	<key name="id" type="number" generator="native" ></key>
	<column name="layout_id" type="number"  />
	<column name="policy_id" type="number"  />
	<column name="name" type="varchar"  length="100" />
	<column name="lcomment" type="varchar" length="200"  />
	<column name="type" type="varchar" length="2" />
	<column name="left" type="number" />
	<column name="top" type="number" />
	<column name="height" type="number" />
	<column name="width" type="number" />
	<column name="zindex" type="number" />
	<column name="font" type="varchar" length="20" />
	<column name="color" type="varchar" length="7" />
	<column name="bgcolor" type="varchar" length="7" />
	<column name="time_format" type="varchar" length="50"/>
	
</schema>

=== LXiong/multimedia-info-distribute-and-manage-system/policy-man/policy-man-db/src/main/dbschema/Policy.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema name="policies" modelName="Policy" paged="true"
xmlns="http://www.dwangel.com/dbschema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.dwangel.com/dbschema dbschema.xsd">
	<key name="id" type="number" generator="native"></key>
	<column name="name" type="varchar" length="100" />
	<column name="comments" type="varchar" length="300"/>
	<column name="start_time" type="datetime" />
	<column name="end_time" type="datetime" />
	<column name="status" type="varchar" length="200" />
	<column name="created_at" type="datetime" noUpdate="true" insertValue="SYSDATE"/>
	<column name="created_by" type="nvarchar" length="50" noUpdate="true"/>
	<column name="updated_at" type="datetime" updateValue="SYSDATE"/>
	<column name="updated_by" type="nvarchar" length="50"/>
	<column name="submit_at" type="datetime"/>
	<column name="submit_by" type="nvarchar" length="50"/>
	<column name="rejected_at" type="datetime"/>
	<column name="rejected_by" type="nvarchar" length="50"/>
	<column name="reason" type="nvarchar" length="250"/>
	<column name="audit_at" type="datetime"/>
	<column name="audit_by" type="nvarchar" length="50"/>
	<column name="published_at" type="datetime" />
	<column name="published_by" type="nvarchar" length="50"/>
	
<!--	<result-map name="withTimeBuckets">-->
<!--		<collection  alias="time_buckets" schemaName="time_buckets" property="timeBuckets"/>		-->
<!--	</result-map>-->
<!--	<result-map name="withPlayItems">-->
<!--		<collection  alias="play_items" schemaName="play_items" property="playItems"/>		-->
<!--	</result-map>-->
<!-- 	<result-map name="withLayout" alias="policy"> -->
<!-- 		<collection  alias="layouts" schemaName="timed_layout" property="layoutList"/>		 -->
<!-- 	</result-map> -->

</schema>

=== LXiong/multimedia-info-distribute-and-manage-system/policy-man/policy-man-db/src/main/dbschema/TimedMedia.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema name="timed_media" modelName="TimedMedia"
	xmlns="http://www.dwangel.com/dbschema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.dwangel.com/dbschema dbschema.xsd">
	<key name="id" type="number" generator="native"></key>
	<column name="code" type="number"/>
	<column name="start_time" type="varchar" length="30"/>
	<column name="end_time" type="varchar" length="30"/>
	<column name="policy_id" type="number"/>
	<column name="layout_id" type="number"/>
	<column name="area_id" type="number"/>
	<column name="playlist_id" type="number"/>
</schema>
