=== LXiong/multimedia-info-distribute-and-manage-system/policy-man/policy-man-db/src/main/dbschema/dbschema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.dwangel.com/dbschema"
	xmlns="http://www.dwangel.com/dbschema" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:element name="schema">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:choice>
				<xsd:element ref="key" />
				<xsd:element ref="complex-key" />
			</xsd:choice>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="column" />
				<xsd:element ref="column-group" />
				<xsd:element ref="default-condition" />
				<xsd:element ref="default-order-by-set" />
				<xsd:element ref="result-map" />
				<xsd:element ref="disabled" />
				<xsd:element ref="alias" />
				<xsd:element ref="aliasColumns" />
			</xsd:choice>
		</xsd:sequence>
		
		<xsd:attribute name="name" type="xsd:string">
			<xsd:annotation>
					<xsd:documentation><![CDATA[
	The unique name of a model schema. If the table name is not definded, used as database table name.
					]]></xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="modelName" type="xsd:string">
			<xsd:annotation>
					<xsd:documentation><![CDATA[
	The unique name of the model Java class.
					]]></xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		
		<xsd:attribute name="tableName" type="xsd:string">
			<xsd:annotation>
					<xsd:documentation><![CDATA[
	The unique name of the model Java class.
					]]></xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		
		<xsd:attribute name="paged" type="xsd:boolean">
			<xsd:annotation>
					<xsd:documentation><![CDATA[
	Whether use pagination.
					]]></xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
</xsd:element>

	<xsd:simpleType name="generatorChoice">
		<xsd:restriction base="xsd:NMTOKEN">
			<xsd:enumeration value="native"/>
			<xsd:enumeration value="sequence"/>
			<xsd:enumeration value="uuid"/>
		</xsd:restriction>
	</xsd:simpleType>

<xsd:element name="key">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="columnDef">
				<xsd:attribute name="generator"  type="generatorChoice">
					<xsd:annotation>
							<xsd:documentation><![CDATA[
   This attribute defines how to generate a key. The choice is native, sequence, uuid. Currently only sequence is supported.
							]]></xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

<xsd:element name="complex-key">
	<xsd:complexType>
		<xsd:choice minOccurs="1" maxOccurs="unbounded">
			<xsd:element ref="column" />
		</xsd:choice>
	</xsd:complexType>
</xsd:element>

	<xsd:complexType name="columnDef">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="type" type="xsd:string" use="required"/>
		<xsd:attribute name="length" type="xsd:integer"/>
		<xsd:attribute name="noUpdate" type="xsd:boolean"/>
		<xsd:attribute name="defaultValue" type="xsd:string"/>
		<xsd:attribute name="updateValue" type="xsd:string"/>
		<xsd:attribute name="insertValue" type="xsd:string"/>
	</xsd:complexType>
<xsd:element name="column" type="columnDef" />

<xsd:element name="column-group">
	<xsd:complexType>
		<xsd:attribute name="name" type="xsd:string" />
	</xsd:complexType>
</xsd:element>

	<xsd:complexType name="searchConditionType">
		<xsd:attribute name="column" type="xsd:string"  />
		<xsd:attribute name="value" type="xsd:string"  />
		<xsd:attribute name="low" type="xsd:string"  />
		<xsd:attribute name="high" type="xsd:string" />
	</xsd:complexType>
	<xsd:complexType name="orderBy">
		<xsd:attribute name="column" type="xsd:string" />
		<xsd:attribute name="asc" type="xsd:boolean" />
	</xsd:complexType>
	
<xsd:element name="default-condition">
	<xsd:complexType >
		<xsd:sequence>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="match" />
				<xsd:element ref="match-value" />
				<xsd:element ref="like" />
				<xsd:element ref="between" />
				<xsd:element ref="order-by" />
			</xsd:choice>
		</xsd:sequence>
	</xsd:complexType>
</xsd:element>
	<xsd:element name="match" type="searchConditionType" />
	<xsd:element name="match-value" type="searchConditionType" />
	<xsd:element name="like" type="searchConditionType" />
	<xsd:element name="between" type="searchConditionType"/>
	<xsd:element name="order-by" type="orderBy"/>

<xsd:element name="default-order-by-set">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element ref="order-by"/>
		</xsd:sequence>
	</xsd:complexType>
</xsd:element>

	<xsd:complexType name="relatedCollection">
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element ref="collection" />
			<xsd:element ref="association" />
		</xsd:choice>
		<xsd:attribute name="schemaName" type="xsd:string" />
		<xsd:attribute name="alias" type="xsd:string" />
		<xsd:attribute name="property" type="xsd:string" />
	</xsd:complexType>
	
	<xsd:complexType name="relatedAssoc">
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element ref="collection" />
			<xsd:element ref="association" />
		</xsd:choice>
		<xsd:attribute name="schemaName" type="xsd:string" />
		<xsd:attribute name="alias" type="xsd:string" />
		<xsd:attribute name="property" type="xsd:string" />
		<xsd:attribute name="column" type="xsd:string" />
	</xsd:complexType>
<xsd:element name="result-map">
	<xsd:complexType>
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element ref="collection" />
			<xsd:element ref="association" />
		</xsd:choice>
		<xsd:attribute name="name" type="xsd:string" />
		<xsd:attribute name="alias" type="xsd:string" />
	</xsd:complexType>
</xsd:element>
	<xsd:element name="collection" type="relatedCollection"></xsd:element>
	<xsd:element name="association" type="relatedAssoc"></xsd:element>
	
<xsd:element name="disabled">
	<xsd:complexType>
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element ref="method" />
		</xsd:choice>
	</xsd:complexType>
</xsd:element>
	<xsd:element name="method" />
	
<xsd:element name="alias">
	<xsd:complexType>
		<xsd:attribute name="name" type="xsd:string" />
	</xsd:complexType>
</xsd:element>

<xsd:element name="aliasColumns">
	<xsd:complexType>
		<xsd:attribute name="name" type="xsd:string" />
	</xsd:complexType>
</xsd:element>

<xsd:element name="description">
	<xsd:annotation>
		<xsd:documentation><![CDATA[
Contains informative text describing the purpose of the enclosing element.
		]]></xsd:documentation>
	</xsd:annotation>
	<xsd:complexType mixed="true">
		<xsd:choice minOccurs="0" maxOccurs="unbounded"/>
	</xsd:complexType>
</xsd:element>

</xsd:schema>

=== LXiong/multimedia-info-distribute-and-manage-system/policy-man/policy-man-db/src/main/dbschema/PublishRecord.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema name="publish_group" modelName="PublishRecord" paged="true"
xmlns="http://www.dwangel.com/dbschema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.dwangel.com/dbschema dbschema.xsd">
	<key name="id" type="number" generator="native"></key>
	<column name="published_at" type="datetime" />
	<column name="policy_number" type="varchar" length="50"/>
	<column name="policy_id" type="number" />
	<column name="type_id" type="number" />
	<column name="group_id" type="number"/>
	<column name="md5" type="varchar" length="100"/>
	<column name="size_bytes" type="number"/>
	<column name="file_path" type="varchar" length="200" />
	
</schema>

=== LXiong/multimedia-info-distribute-and-manage-system/policy-man/policy-man-db/src/main/dbschema/TimedLayout.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema name="timed_layout" modelName="TimedLayout" paged="true"
xmlns="http://www.dwangel.com/dbschema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.dwangel.com/dbschema dbschema.xsd">
	<key name="id" generator="native" type="number" />
	<column name="policy_id" type="number"/>
	<column name="layout_id" type="number"/>
	<column name="start_time" type="varchar" length="5" />
	<column name="end_time" type="varchar" length="5" />
	<column name="name" type="varchar" length="100" />
	<column name="use_percent" type="boolean" length="1"/>
	<column name="width" type="number" />
	<column name="height" type="number" />
	<column name="lcomment" type="varchar" length="200" />
	<column name="fullscreen" type="boolean" length="1"/>
	
	<result-map name="withArea" alias="tl">
		<collection alias="ta" schemaName="timed_area" property="areas">
			<collection alias="tpl" schemaName="timed_list" property="playLists">
				<collection alias="tmd" schemaName="timed_media" property="medias"></collection>
			</collection>
		</collection>
	</result-map>
	
<!-- 	<aliasColumns name="tl"/> -->
	<alias name="tl" />
</schema>

=== LXiong/multimedia-info-distribute-and-manage-system/policy-man/policy-man-db/src/main/dbschema/Authority.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema name="mm_authority" modelName="Authority"
	xmlns="http://www.dwangel.com/dbschema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.dwangel.com/dbschema dbschema.xsd"
>
	<key name="id" type="number"></key>
	<column name="type" type="int" />
	<column name="name" type="varchar" length="50" />
	<column name="locale_zh_cn" type="nvarchar" length="100" />
	<default-order-by-set>
		<order-by column="type"/>
	</default-order-by-set>
	<alias name="auth" />
</schema>

=== LXiong/multimedia-info-distribute-and-manage-system/policy-man/policy-man-db/src/main/dbschema/TimedPlayList.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema name="timed_list" modelName="TimedList"
	xmlns="http://www.dwangel.com/dbschema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.dwangel.com/dbschema dbschema.xsd"
>
	<key name="id" type="number" generator="native" />
	<column name="policy_id" type="number"  />
	<column name="area_id" type="number"  />
	<column name="type" type="varchar" length="2" />
	<column name="start_time" type="varchar" length="5"/>
	<column name="end_time" type="varchar" length="5"/>
	<column name="loop" type="boolean" length="1" />
	<column name="content" type="nvarchar" length="1000" />
	<default-order-by-set>
		<order-by column="start_time"/>
	</default-order-by-set>
	
	<alias name="tpl" />
</schema>

=== LXiong/multimedia-info-distribute-and-manage-system/policy-man/policy-man-db/src/main/dbschema/ManUser.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema name="man_users" modelName="User" paged="true"
xmlns="http://www.dwangel.com/dbschema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.dwangel.com/dbschema dbschema.xsd"
>
	<key name="username" type="nvarchar" length="30"></key>
	<column name="password" type="varchar" length="64" noUpdate="true" />
	<column name="disp_name" type="nvarchar" length="64" />
	<column name="email" type="varchar" length="100" />
	<column name="phone" type="varchar" length="20" />
	<column name="enabled" type="boolean" length="1" defaultValue="'1'" />
	<column name="last_login" type="datetime" />
	<column-group name="trackModify" />
	
	<default-condition>
		<match column="username" />
		<match column="enabled" />
	</default-condition>
</schema>

=== LXiong/multimedia-info-distribute-and-manage-system/policy-man/policy-man-db/src/main/dbschema/Layout.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema name="layout" modelName="Layout" paged="true"
xmlns="http://www.dwangel.com/dbschema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.dwangel.com/dbschema dbschema.xsd">
	<key name="id" type="number" generator="native"></key>
	<column name="name" type="varchar" length="100" />
	<column name="use_percent" type="boolean" length="1"/>
	<column name="width" type="number" />
	<column name="height" type="number" />
	<column name="lcomment" type="varchar" length="200" />
	
	<result-map name="withArea" alias="layout">
		<collection  alias="area" schemaName="area" property="areas"/>		
	</result-map>
</schema>

=== LXiong/multimedia-info-distribute-and-manage-system/policy-man/policy-man-db/src/main/dbschema/StbGroupLevelTwo.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema name="stbGroupLevelTwo" modelName="StbGroupLevelTwo" tableName="GROUPS" paged="true"
xmlns="http://www.dwangel.com/dbschema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.dwangel.com/dbschema dbschema.xsd">
	<key name="group_id" type="number"></key>
	<column name="group_name" type="varchar" length="50"/>
	<column name="type_id" type="number"/>
	<column name="group_description" type="varchar" length="200" />
	<column name="conf_id" type="number"/>
	<column name="packageid" type="number"/>
	
	<alias name="sgt"/>
</schema>

=== LXiong/multimedia-info-distribute-and-manage-system/policy-man/policy-man-db/src/main/dbschema/Video.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema name="videos" modelName="Video"
xmlns="http://www.dwangel.com/dbschema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.dwangel.com/dbschema dbschema.xsd"
>
	<key name="code" type="varchar" length="64"></key>
	<column name="origin_name" type="nvarchar" length="100" noUpdate="true" />
	<column name="file_name" type="nvarchar" length="100" />
	<column name="name" type="nvarchar" length="30" />
	<column name="tag" type="nvarchar" length="100" />
	<column name="description" type="nvarchar" length="300" />
	<column name="status" type="varchar" length="50" />
	<column name="live_time_start" type="datetime" />
	<column name="live_time_end" type="datetime" />
	<column name="submitter" type="nvarchar" length="50" />
	<column name="submit_at" type="datetime" />
	<column name="auditor" type="nvarchar" length="50" noUpdate="true" />
	<column name="audit_at" type="datetime" noUpdate="true" />
	<column name="width" type="number" />
	<column name="height" type="number" />
	<column name="play_time" type="number" />
	<column name="discrim" type="nvarchar" length="50" />
	<column name="media_type" type="nvarchar" length="20" />
	<column name="media_size" type="number" noUpdate="true" />
	
	<default-condition>
		<like column="name" />
		<match column="media_type" />
		<between column="audit_at" high="auditAtEnd" low="auditAtStart"/>
	</default-condition>
	
	<alias name="v"/>
</schema>
